<template><div><div class="custom-container tip"><p class="custom-container-title">提示</p>
<p>目前框架提供了三种监控数据采集方式，通过 collectType 属性配置监控指标采集类型，默认 logging</p>
<p>1.jsonlog：线程池指标数据会以 json 格式输出到指定的文件里</p>
<p>2.micrometer：采用监控门面，通过引入相关 micrometer 依赖采集到相应的存储平台里（如 Prometheus，InfluxDb...）</p>
<p>3.暴雷 Endpoint端点，可以通过 http 方式实时获取指标数据</p>
</div>
<h3 id="micrometer" tabindex="-1"><a class="header-anchor" href="#micrometer" aria-hidden="true">#</a> micrometer</h3>
<p>引入prometheus（也可以用其他） 对应依赖，job配置后prometheus管理台看到如下图所示，说明已经开始正常采集指标配置</p>
<p><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/435f0a69790946f8bff7761c40a0a0db~tplv-k3u1fbpfcp-zoom-1.image" alt="采集指标" loading="lazy"></p>
<h3 id="logging" tabindex="-1"><a class="header-anchor" href="#logging" aria-hidden="true">#</a> logging</h3>
<p>指标数据以 json 日志格式输出磁盘，地址 <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mrow><mi>l</mi><mi>o</mi><mi>g</mi><mi>P</mi><mi>a</mi><mi>t</mi><mi>h</mi></mrow><mi mathvariant="normal">/</mi><mi>d</mi><mi>y</mi><mi>n</mi><mi>a</mi><mi>m</mi><mi>i</mi><mi>c</mi><mi>t</mi><mi>p</mi><mi mathvariant="normal">/</mi></mrow><annotation encoding="application/x-tex">{logPath}/dynamictp/</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:1em;vertical-align:-0.25em;"></span><span class="mord"><span class="mord mathnormal" style="margin-right:0.01968em;">l</span><span class="mord mathnormal">o</span><span class="mord mathnormal" style="margin-right:0.03588em;">g</span><span class="mord mathnormal" style="margin-right:0.13889em;">P</span><span class="mord mathnormal">a</span><span class="mord mathnormal">t</span><span class="mord mathnormal">h</span></span><span class="mord">/</span><span class="mord mathnormal">d</span><span class="mord mathnormal" style="margin-right:0.03588em;">y</span><span class="mord mathnormal">nami</span><span class="mord mathnormal">c</span><span class="mord mathnormal">tp</span><span class="mord">/</span></span></span></span>{appName}.monitor.log</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token punctuation">{</span><span class="token string">"datetime"</span><span class="token builtin class-name">:</span> <span class="token string">"2022-04-17 11:35:15.208"</span>, <span class="token string">"app_name"</span><span class="token builtin class-name">:</span> <span class="token string">"dynamic-tp-nacos-cloud-demo"</span>, <span class="token string">"thread_pool_metrics"</span><span class="token builtin class-name">:</span> <span class="token punctuation">{</span><span class="token string">"activeCount"</span>:0,<span class="token string">"queueSize"</span>:0,<span class="token string">"largestPoolSize"</span>:0,<span class="token string">"poolSize"</span>:0,<span class="token string">"rejectHandlerName"</span><span class="token builtin class-name">:</span><span class="token string">"CallerRunsPolicy"</span>,<span class="token string">"queueCapacity"</span>:2000,<span class="token string">"fair"</span>:false,<span class="token string">"queueTimeoutCount"</span>:0,<span class="token string">"rejectCount"</span>:0,<span class="token string">"waitTaskCount"</span>:0,<span class="token string">"taskCount"</span>:0,<span class="token string">"runTimeoutCount"</span>:0,<span class="token string">"queueRemainingCapacity"</span>:2000,<span class="token string">"corePoolSize"</span>:4,<span class="token string">"queueType"</span><span class="token builtin class-name">:</span><span class="token string">"VariableLinkedBlockingQueue"</span>,<span class="token string">"completedTaskCount"</span>:0,<span class="token string">"dynamic"</span>:true,<span class="token string">"maximumPoolSize"</span>:6,<span class="token string">"poolName"</span><span class="token builtin class-name">:</span><span class="token string">"dtpExecutor1"</span><span class="token punctuation">}</span><span class="token punctuation">}</span>
<span class="token punctuation">{</span><span class="token string">"datetime"</span><span class="token builtin class-name">:</span> <span class="token string">"2022-04-17 11:35:15.209"</span>, <span class="token string">"app_name"</span><span class="token builtin class-name">:</span> <span class="token string">"dynamic-tp-nacos-cloud-demo"</span>, <span class="token string">"thread_pool_metrics"</span><span class="token builtin class-name">:</span> <span class="token punctuation">{</span><span class="token string">"activeCount"</span>:0,<span class="token string">"queueSize"</span>:0,<span class="token string">"largestPoolSize"</span>:0,<span class="token string">"poolSize"</span>:0,<span class="token string">"rejectHandlerName"</span><span class="token builtin class-name">:</span><span class="token string">"CallerRunsPolicy"</span>,<span class="token string">"queueCapacity"</span>:2000,<span class="token string">"fair"</span>:false,<span class="token string">"queueTimeoutCount"</span>:0,<span class="token string">"rejectCount"</span>:0,<span class="token string">"waitTaskCount"</span>:0,<span class="token string">"taskCount"</span>:0,<span class="token string">"runTimeoutCount"</span>:0,<span class="token string">"queueRemainingCapacity"</span>:2000,<span class="token string">"corePoolSize"</span>:2,<span class="token string">"queueType"</span><span class="token builtin class-name">:</span><span class="token string">"TaskQueue"</span>,<span class="token string">"completedTaskCount"</span>:0,<span class="token string">"dynamic"</span>:true,<span class="token string">"maximumPoolSize"</span>:4,<span class="token string">"poolName"</span><span class="token builtin class-name">:</span><span class="token string">"dtpExecutor2"</span><span class="token punctuation">}</span><span class="token punctuation">}</span>
<span class="token punctuation">{</span><span class="token string">"datetime"</span><span class="token builtin class-name">:</span> <span class="token string">"2022-04-17 11:35:15.209"</span>, <span class="token string">"app_name"</span><span class="token builtin class-name">:</span> <span class="token string">"dynamic-tp-nacos-cloud-demo"</span>, <span class="token string">"thread_pool_metrics"</span><span class="token builtin class-name">:</span> <span class="token punctuation">{</span><span class="token string">"activeCount"</span>:0,<span class="token string">"queueSize"</span>:0,<span class="token string">"largestPoolSize"</span>:0,<span class="token string">"poolSize"</span>:0,<span class="token string">"queueCapacity"</span>:2147483647,<span class="token string">"fair"</span>:false,<span class="token string">"queueTimeoutCount"</span>:0,<span class="token string">"rejectCount"</span>:0,<span class="token string">"waitTaskCount"</span>:0,<span class="token string">"taskCount"</span>:0,<span class="token string">"runTimeoutCount"</span>:0,<span class="token string">"queueRemainingCapacity"</span>:2147483647,<span class="token string">"corePoolSize"</span>:1,<span class="token string">"queueType"</span><span class="token builtin class-name">:</span><span class="token string">"LinkedBlockingQueue"</span>,<span class="token string">"completedTaskCount"</span>:0,<span class="token string">"dynamic"</span>:false,<span class="token string">"maximumPoolSize"</span>:1,<span class="token string">"poolName"</span><span class="token builtin class-name">:</span><span class="token string">"commonExecutor"</span><span class="token punctuation">}</span><span class="token punctuation">}</span>
<span class="token punctuation">{</span><span class="token string">"datetime"</span><span class="token builtin class-name">:</span> <span class="token string">"2022-04-17 11:35:15.209"</span>, <span class="token string">"app_name"</span><span class="token builtin class-name">:</span> <span class="token string">"dynamic-tp-nacos-cloud-demo"</span>, <span class="token string">"thread_pool_metrics"</span><span class="token builtin class-name">:</span> <span class="token punctuation">{</span><span class="token string">"activeCount"</span>:0,<span class="token string">"queueSize"</span>:0,<span class="token string">"largestPoolSize"</span>:100,<span class="token string">"poolSize"</span>:100,<span class="token string">"queueCapacity"</span>:2147483647,<span class="token string">"fair"</span>:false,<span class="token string">"queueTimeoutCount"</span>:0,<span class="token string">"rejectCount"</span>:0,<span class="token string">"waitTaskCount"</span>:0,<span class="token string">"taskCount"</span>:177,<span class="token string">"runTimeoutCount"</span>:0,<span class="token string">"queueRemainingCapacity"</span>:2147483647,<span class="token string">"corePoolSize"</span>:100,<span class="token string">"queueType"</span><span class="token builtin class-name">:</span><span class="token string">"TaskQueue"</span>,<span class="token string">"completedTaskCount"</span>:177,<span class="token string">"dynamic"</span>:false,<span class="token string">"maximumPoolSize"</span>:400,<span class="token string">"poolName"</span><span class="token builtin class-name">:</span><span class="token string">"tomcatWebServerTp"</span><span class="token punctuation">}</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="endpoint" tabindex="-1"><a class="header-anchor" href="#endpoint" aria-hidden="true">#</a> endpoint</h3>
<p>暴露端点(dynamic-tp)，可以通过 http 方式请求</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token punctuation">[</span>
    <span class="token punctuation">{</span>
        <span class="token property">"pool_name"</span><span class="token operator">:</span> <span class="token string">"remoting-call"</span><span class="token punctuation">,</span>
        <span class="token property">"core_pool_size"</span><span class="token operator">:</span> <span class="token number">6</span><span class="token punctuation">,</span>
        <span class="token property">"maximum_pool_size"</span><span class="token operator">:</span> <span class="token number">12</span><span class="token punctuation">,</span>
        <span class="token property">"queue_type"</span><span class="token operator">:</span> <span class="token string">"SynchronousQueue"</span><span class="token punctuation">,</span>
        <span class="token property">"queue_capacity"</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
        <span class="token property">"queue_size"</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
        <span class="token property">"fair"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
        <span class="token property">"queue_remaining_capacity"</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
        <span class="token property">"active_count"</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
        <span class="token property">"task_count"</span><span class="token operator">:</span> <span class="token number">21760</span><span class="token punctuation">,</span>
        <span class="token property">"completed_task_count"</span><span class="token operator">:</span> <span class="token number">21760</span><span class="token punctuation">,</span>
        <span class="token property">"largest_pool_size"</span><span class="token operator">:</span> <span class="token number">12</span><span class="token punctuation">,</span>
        <span class="token property">"pool_size"</span><span class="token operator">:</span> <span class="token number">6</span><span class="token punctuation">,</span>
        <span class="token property">"wait_task_count"</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
        <span class="token property">"reject_count"</span><span class="token operator">:</span> <span class="token number">124662</span><span class="token punctuation">,</span>
        <span class="token property">"reject_handler_name"</span><span class="token operator">:</span> <span class="token string">"CallerRunsPolicy"</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
