<template><div><p><strong>接入步骤</strong></p>
<p>1.引入相应配置中心的依赖，具体见下述 mavne依赖</p>
<p>2.配置中心配置线程池实例，配置见下述（给出的是全配置项，不用的可以删除）</p>
<p>3.启动类加 @EnableDynamicTp 注解</p>
<p>4.使用 @Resource 或 @Autowired 进行依赖注入，或通过 DtpRegistry.getDtpExecutor(&quot;name&quot;)获取</p>
<p>5.通过以上4步就可以使用了，是不是感觉很简单啊</p>
<div class="custom-container tip"><p class="custom-container-title">启动日志输出</p>
<p>服务启动看到有如下日志输出说明接入成功</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token operator">|</span>  __ <span class="token punctuation">\</span>                            <span class="token punctuation">(</span>_<span class="token punctuation">)</span> <span class="token operator">|</span>__   __<span class="token operator">|</span>
<span class="token operator">|</span> <span class="token operator">|</span>  <span class="token operator">|</span> <span class="token operator">|</span>_   _ _ __   __ _ _ __ ___  _  ___<span class="token operator">|</span> <span class="token operator">|</span>_ __
<span class="token operator">|</span> <span class="token operator">|</span>  <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token string">'_ \ / _` | '</span>_ ` _ <span class="token operator">|</span> <span class="token operator">|</span>/ __<span class="token operator">|</span> <span class="token operator">|</span> '_ <span class="token punctuation">\</span>
<span class="token operator">|</span> <span class="token operator">|</span>__<span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span>_<span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token punctuation">(</span>_<span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span> <span class="token punctuation">(</span>__<span class="token operator">|</span> <span class="token operator">|</span> <span class="token operator">|</span>_<span class="token punctuation">)</span> <span class="token operator">|</span>
<span class="token operator">|</span>_____/ __, <span class="token operator">|</span>_<span class="token operator">|</span> <span class="token operator">|</span>_<span class="token operator">|</span>__,_<span class="token operator">|</span>_<span class="token operator">|</span> <span class="token operator">|</span>_<span class="token operator">|</span> <span class="token operator">|</span>_<span class="token operator">|</span>_<span class="token operator">|</span>___<span class="token operator">|</span>_<span class="token operator">|</span> .__/
         __/ <span class="token operator">|</span>                              <span class="token operator">|</span> <span class="token operator">|</span>
        <span class="token operator">|</span>___/                               <span class="token operator">|</span>_<span class="token operator">|</span>
 :: Dynamic Thread Pool ::

DynamicTp register dtpExecutor, source: beanPostProcessor, executor: DtpMainPropWrapper<span class="token punctuation">(</span>dtpName<span class="token operator">=</span>dynamic-tp-test-1, <span class="token assign-left variable">corePoolSize</span><span class="token operator">=</span><span class="token number">6</span>, <span class="token assign-left variable">maxPoolSize</span><span class="token operator">=</span><span class="token number">8</span>, <span class="token assign-left variable">keepAliveTime</span><span class="token operator">=</span><span class="token number">50</span>, <span class="token assign-left variable">queueType</span><span class="token operator">=</span>VariableLinkedBlockingQueue, <span class="token assign-left variable">queueCapacity</span><span class="token operator">=</span><span class="token number">200</span>, <span class="token assign-left variable">rejectType</span><span class="token operator">=</span>RejectedCountableCallerRunsPolicy, <span class="token assign-left variable">allowCoreThreadTimeOut</span><span class="token operator">=</span>false<span class="token punctuation">)</span>

DtpRegistry initialization end, remote dtpExecutors: <span class="token punctuation">[</span>dtpExecutor1, dtpExecutor2<span class="token punctuation">]</span>, <span class="token builtin class-name">local</span> dtpExecutors: <span class="token punctuation">[</span>ioIntensiveExecutor<span class="token punctuation">]</span>, <span class="token builtin class-name">local</span> commonExecutors: <span class="token punctuation">[</span>commonExecutor<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div>
<div class="custom-container warning"><p class="custom-container-title">注意</p>
<p>1.普通 JUC 线程池想要被监控，可以 @Bean 定义时加 @DynamicTp 注解</p>
<p>2.动态线程池实例服务启动时会根据配置中心的配置动态注册到Spring容器中，建议不要用@Bean编程式重复声明同一线程池实例，直接配置在配置中心就行</p>
<p>3.阻塞队列只有 VariableLinkedBlockingQueue 类型可以修改 capacity，该类型功能和 LinkedBlockingQueue 相似， 只是 capacity 不是
final 类型，可以修改， VariableLinkedBlockingQueue 参考 RabbitMq 的实现</p>
</div>
</div></template>
