{
 "title": "线程池监控（DynamicTp）",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(app_name)" } },
   {
    "name": "threadpool",
    "label": "threadpool",
    "query": {
     "query": "label_values({app_name=\"$application\"}, thread_pool_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "核心线程数",
   "type": "piechart",
   "description": "核心线程数",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thread_pool_core_size{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "最大线程数",
   "type": "piechart",
   "description": "最大线程数",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thread_pool_maximum_size{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tps",
   "type": "piechart",
   "description": "tps",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thread_pool_tps{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tp99 耗时",
   "type": "piechart",
   "description": "tp99 耗时",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "thread_pool_completed_task_time_tp99{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "当前线程数",
   "type": "timeseries",
   "description": "当前线程数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "thread_pool_current_size{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "活跃线程数",
   "type": "timeseries",
   "description": "活跃线程数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "thread_pool_active_count{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "任务队列大小",
   "type": "timeseries",
   "description": "任务队列大小",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "thread_pool_queue_size{app_name=\"$application\", thread_pool_name=\"$threadpool\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "任务队列剩余大小",
   "type": "timeseries",
   "description": "任务队列剩余大小",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thread_pool_queue_remaining_capacity{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "完成任务数",
   "type": "timeseries",
   "description": "完成任务数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_count{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "拒绝任务数",
   "type": "timeseries",
   "description": "拒绝任务数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thread_pool_reject_count{app_name=\"$application\", thread_pool_name=\"$threadpool\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "执行超时任务数",
   "type": "timeseries",
   "description": "执行超时任务数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "thread_pool_run_timeout_count{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "排队超时任务数",
   "type": "timeseries",
   "description": "排队超时任务数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "thread_pool_queue_timeout_count{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tps",
   "type": "timeseries",
   "description": "tps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "thread_pool_tps{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tp999 耗时",
   "type": "timeseries",
   "description": "tp999 耗时",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_time_tp999{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tp99 耗时",
   "type": "timeseries",
   "description": "tp99 耗时",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_time_tp99{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tp95 耗时",
   "type": "timeseries",
   "description": "tp95 耗时",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_time_tp95{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tp90 耗时",
   "type": "timeseries",
   "description": "tp90 耗时",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_time_tp90{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tp50 耗时",
   "type": "timeseries",
   "description": "tp50 耗时",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_time_tp50{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "任务平均耗时",
   "type": "timeseries",
   "description": "任务平均耗时",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_time_avg{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "任务最大耗时",
   "type": "timeseries",
   "description": "任务最大耗时",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_time_max{app_name=\"$application\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}