server:
  port: 9100

spring:
  application:
    name: dynamic-tp-admin-demo
  profiles:
    active: dev
  redis:
    host: ${redis:localhost}
    port: 6379

dynamictp:
  clientName: dynamic-tp-admin-demo
  adminEnabled: true

#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure: DEBUG