{
 "title": "线程池监控（DynamicTp）",
 "description": "线程池监控",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$namespace\",container=~\"$container\"},pod)"
    }
   },
   {
    "name": "threadpool",
    "label": "ThreadPoolName",
    "query": {
     "query": "label_values(thread_pool_current_size{app_kubernetes_io_instance=\"$container\", kubernetes_pod_name=~\"$pod\"},thread_pool_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "当前线程数",
   "type": "timeseries",
   "description": "当前线程数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "thread_pool_current_size{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\",pod=\"$pod\",thread_pool_name=~\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "活跃线程数",
   "type": "timeseries",
   "description": "活跃线程数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "thread_pool_active_count{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\",pod=\"$pod\",thread_pool_name=~\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "任务队列大小",
   "type": "timeseries",
   "description": "任务队列大小",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "thread_pool_queue_size{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\",pod=\"$pod\",thread_pool_name=~\"$threadpool\"}\n",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "任务队列剩余大小",
   "type": "timeseries",
   "description": "任务队列剩余大小",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thread_pool_queue_remaining_capacity{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\",pod=\"$pod\",thread_pool_name=~\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "完成任务数",
   "type": "timeseries",
   "description": "完成任务数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_count{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\",pod=\"$pod\",thread_pool_name=~\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "拒绝任务数",
   "type": "timeseries",
   "description": "拒绝任务数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thread_pool_reject_count{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\",pod=\"$pod\",thread_pool_name=~\"$threadpool\"}\n",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "执行超时任务数",
   "type": "timeseries",
   "description": "执行超时任务数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "thread_pool_run_timeout_count{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\",pod=\"$pod\",thread_pool_name=~\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "队列等待超时任务数",
   "type": "timeseries",
   "description": "队列等待超时任务数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "thread_pool_queue_timeout_count{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\",pod=\"$pod\",thread_pool_name=~\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  }
 ]
}