name: build jvmti

on: [push]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/jvmti/jvmti-build
          mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: jvmti/jvmti-build/target/classes/lib*
          if-no-files-found: error

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/jvmti/jvmti-build
          mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: jvmti/jvmti-build/target/classes/lib*
          if-no-files-found: error

  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/jvmti/jvmti-build
          mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: lib
          path: jvmti/jvmti-build/target/classes/*.dll
          if-no-files-found: error
