{
 "title": "线程池监控",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(thread_pool_reject_count, app_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(thread_pool_reject_count, instance)"
    }
   },
   {
    "name": "threadpool",
    "label": "ThreadPoolName",
    "query": {
     "query": "label_values(thread_pool_reject_count, thread_pool_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "当前池大小",
   "type": "timeseries",
   "description": "当前池大小",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "thread_pool_current_size{app_name=\"$application\", instance=\"$instance\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "任务队列剩余大小",
   "type": "timeseries",
   "description": "任务队列剩余大小",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thread_pool_queue_remaining_capacity{app_name=\"$application\", instance=\"$instance\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "完成任务数",
   "type": "timeseries",
   "description": "完成任务数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "thread_pool_completed_task_count{app_name=\"$application\", instance=\"$instance\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "拒绝任务数",
   "type": "timeseries",
   "description": "拒绝任务数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "thread_pool_reject_count{app_name=\"$application\", instance=\"$instance\", thread_pool_name=\"$threadpool\"}\n",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "活跃线程数",
   "type": "timeseries",
   "description": "活跃线程数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "thread_pool_active_count{app_name=\"$application\", instance=\"$instance\", thread_pool_name=\"$threadpool\"}",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  },
  {
   "title": "任务队列大小",
   "type": "timeseries",
   "description": "任务队列大小",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "thread_pool_queue_size{app_name=\"$application\", instance=\"$instance\", thread_pool_name=\"$threadpool\"}\n",
     "legendFormat": "{{thread_pool_name}}"
    }
   ]
  }
 ]
}